### PR TITLE
chore: build workflow test

### PR DESCRIPTION
**Pull request by PalmDevs**

### CODE REVIEW

**Comment by PalmDevs** [comment]
@void6670 :trollface:

**Comment by PalmDevs** [comment]
@xafn come

**Comment by xafn** [comment]
hi

**Review by xafn — APPROVED** [review]
!build

**Comment by PalmDevs** [comment]
YES OMG

**Comment by PalmDevs** [comment]
GAHGUDASH FGS:GH
image

**Comment by PalmDevs** [comment]
i love adn @xafn

**Comment by xafn** [comment]
wow this is acc pretty cool

**Review by xafn — APPROVED** [review]
my balls itch

**Review by xafn — APPROVED** [review]
some comment, then i !build

**Review by xafn — APPROVED** [review]
!builddd

**Review by xafn — APPROVED** [review]
!build

**Review by xafn — APPROVED** [review]
!build

**Review by xafn — APPROVED** [review]
no

**Comment by PalmDevs** [comment]
gon

**Pull request closed without merging**
