### PR TITLE
chore: add amogus

### PR DESCRIPTION
**Pull request by Axelen123**
when the manager sus

### CODE REVIEW

**Comment by PalmDevs** [comment]
real

**Comment by Axelen123** [comment]
you will merge :trollface:

**Review by PalmDevs — APPROVED** [review]

**Comment by PalmDevs** [comment]
oops im stupid

**Review by PalmDevs — APPROVED** [review]
:trollface:

!build

**Comment by PalmDevs** [comment]
gah it skiped again

**Comment by Axelen123** [comment]
trolley

**Review by PalmDevs — APPROVED** [review]
!build

**Comment by PalmDevs** [comment]
i hate github actions!!!

**Comment by Axelen123** [comment]
> i hate github actions!!!

cope

**Review by PalmDevs — APPROVED** [review]

**Review by PalmDevs — APPROVED** [review]
dn

!build

**Review by PalmDevs — APPROVED** [review]
CANCEL THE CURRENT BUILD RUN NOWWWW


!build

**Comment by Axelen123** [comment]
deez

**Review by PalmDevs — APPROVED** [review]
!build

**Review by PalmDevs — APPROVED** [review]
!build

**Review by PalmDevs — APPROVED** [review]
dn

**Review by PalmDevs — APPROVED** [review]
!build

**Review by PalmDevs — APPROVED** [review]
!build

**Review by PalmDevs — APPROVED** [review]
!build

**Review by PalmDevs — APPROVED** [review]
!build

**Review by PalmDevs — APPROVED** [review]
!build

**Review by PalmDevs — APPROVED** [review]
!build

**Review by PalmDevs — APPROVED** [review]
!build

**Review by PalmDevs — APPROVED** [review]
!build

**Review by PalmDevs — APPROVED** [review]
!build

**Review by PalmDevs — APPROVED** [review]
dn

!build

**Pull request closed without merging**
